-- ============================================================
-- Sample-question difficulty inference + per-topic question style guide
-- Run in Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- Safe to re-run — every statement is idempotent.
-- Run AFTER 20260620b_pages_dedup_requests_disputes.sql (depends on
-- knowledge_chunks.needs_review existing, though that's not enforced here).
-- ============================================================

-- 1. DIFFICULTY INFERENCE ON SAMPLE-QUESTION CHUNKS
-- Populated only for chunks extracted in "questions" mode (sample papers).
-- Claude judges how hard the original sample question was and why — this
-- becomes part of the per-topic style guide used as a reference when
-- generating new AI questions.
-- ============================================================
ALTER TABLE knowledge_chunks ADD COLUMN IF NOT EXISTS inferred_difficulty TEXT
  CHECK (inferred_difficulty IN ('easy', 'medium', 'hard'));
ALTER TABLE knowledge_chunks ADD COLUMN IF NOT EXISTS difficulty_reason TEXT;

-- 2. PER-TOPIC QUESTION STYLE GUIDE
-- A synthesized, admin-editable document describing how this topic's sample
-- questions are phrased, what answers/distractors look like, and what makes
-- a question easy/medium/hard. Generated by Claude from the topic's chunks,
-- then editable by the admin, then injected into question-generation prompts.
-- ============================================================
ALTER TABLE topics ADD COLUMN IF NOT EXISTS question_style_guide TEXT;
ALTER TABLE topics ADD COLUMN IF NOT EXISTS style_guide_updated_at TIMESTAMPTZ;
